In [3]:
import pandas as pd
from rake_nltk import Rake
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.feature_extraction.text import CountVectorizer
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.feature_extraction.text import TfidfVectorizer,CountVectorizer
from sklearn.metrics.pairwise import linear_kernel,cosine_similarity
from ast import literal_eval
import warnings
warnings.filterwarnings('ignore')
%matplotlib inline
df = pd.read_csv('data/Topics.csv')
df.head()

,Title,Director,Country,Year,Decade,Duration,Description,Url,averageRating,numVotes,Topic,Topic Description
0,2 or 3 Things I Know About Her,Jean-Luc Godard,France,1967,1960s,1:27,In 2 OR 3 THINGS I KNOW ABOUT HER (2 OU 3 CHOS...,https://www.criterionchannel.com/2-or-3-things...,6.8,6576,88,"godard, anna, marriage, star, iconic, french_w..."
1,3 Faces,Jafar Panahi,Iran,2018,2010s,1:40,Iranian master Jafar Panahi’s fourth feature s...,https://www.criterionchannel.com/3-faces,7.1,3331,90,"day, long, narrative, school, 1950s, drive, mo..."
2,"4 Months, 3 Weeks and 2 Days",Cristian Mungiu,Romania,2007,2000s,1:53,Romanian filmmaker Cristian Mungiu shot to int...,https://www.criterionchannel.com/4-months-3-we...,7.9,57029,90,"day, long, narrative, school, 1950s, drive, mo..."
3,"The VI Olympic Winter Games, Oslo 1952",Tankred Ibsen,Norway,1952,1950s,1:43,Director Tancred Ibsen's penchant for depictin...,https://www.criterionchannel.com/the-vi-olympi...,5.9,48,71,"game, film, search, individual, approach, figu..."
4,8½,Federico Fellini,Italy,1963,1960s,2:19,"Marcello Mastroianni plays Guido Anselmi, a di...",https://www.criterionchannel.com/81-2,8.0,109896,85,"filmmaker, life, journey, acclaimed, footage, ..."

In [5]:
from textblob import TextBlob
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer

In [7]:
#load the descriptions into textblob
desc_blob = [TextBlob(desc) for desc in df['Description']]
#add the sentiment metrics to the dataframe
df['tb_Pol'] = [b.sentiment.polarity for b in desc_blob]
df['tb_Subj'] = [b.sentiment.subjectivity for b in desc_blob]
#show dataframe

,Title,Director,Country,Year,Decade,Duration,Description,Url,averageRating,numVotes,Topic,Topic Description,tb_Pol,tb_Subj
611,I Was a Teenage Zombie,John Elias Michalakis,United States,1987,1980s,1:31,A group of teens looking to score some weed un...,https://www.criterionchannel.com/i-was-a-teena...,4.5,729,56,"music, musical, score, cinematic, song, jazz, ...",-0.80,1.000000
562,Hunter in the Dark,Hideo Gosha,Japan,1979,1970s,2:17,"In Hideo Gosha's film, loyalty and ambition le...",https://www.criterionchannel.com/hunter-in-the...,6.9,425,81,"samurai, godzilla, monster, series, make, eart...",-0.75,0.750000
1354,Walpurgis Night,Gustaf Edgren,Sweden,1935,1930s,1:19,Meant as a day to celebrate the arrival of spr...,https://www.criterionchannel.com/walpurgis-night,6.0,317,10,"wife, home, marriage, desperate, charles, leaf...",-0.60,0.933333
210,Checking Out,David Leland,United States,1989,1980s,1:35,"After his friend suffers a fatal heart attack,...",https://www.criterionchannel.com/checking-out,4.8,396,11,"work, heart, deeply, beloved, run, owner, henr...",-0.60,0.700000
218,Chinese Odyssey 2002,Jeffrey Lau,Hong Kong,2002,2000s,1:30,"An Emperor and a princess, both desperate for ...",https://www.criterionchannel.com/chinese-odyss...,7.0,2312,15,"death, classic, power, final, maria, john, ric...",-0.60,1.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1228,Tales of a Golden Geisha,Juzo Itami,Japan,1990,1990s,1:58,Nobuko Miyamoto stars as a geisha who brings g...,https://www.criterionchannel.com/tales-of-a-go...,6.4,214,81,"samurai, godzilla, monster, series, make, eart...",0.70,0.600000
1137,"Sing, Young People!",Keisuke Kinoshita,Japan,1963,1960s,1:26,A college student receives a surprising offer ...,https://www.criterionchannel.com/sing-young-pe...,6.3,55,98,"young, student, kinoshita, friend, directed_ke...",0.70,0.500000
1368,Welcome Danger,Clyde Bruckman,United States,1929,1920s,1:54,"Harold Bledsoe, a botanist and the son of a su...",https://www.criterionchannel.com/welcome-danger,6.0,687,24,"force, crime, seemingly, north, english, clima...",0.75,0.950000
714,Lone Wolf and Cub: Sword of Vengeance,Kenji Misumi,Japan,1972,1970s,1:23,The inaugural film in the LONE WOLF AND CUB se...,https://www.criterionchannel.com/lone-wolf-and...,7.8,7247,56,"music, musical, score, cinematic, song, jazz, ...",0.80,0.916667
1282,Tokyo-ga,Wim Wenders,West Germany,1985,1980s,1:33,On the streets of Tokyo and in meetings with s...,https://www.criterionchannel.com/tokyo-ga,7.4,2639,92,"legendary, jean, mysterious, writer, world, ar...",1.00,1.000000

In [8]:
df.sort_values('tb_Pol')

,Title,Director,Country,Year,Decade,Duration,Description,Url,averageRating,numVotes,Topic,Topic Description,tb_Pol,tb_Subj
611,I Was a Teenage Zombie,John Elias Michalakis,United States,1987,1980s,1:31,A group of teens looking to score some weed un...,https://www.criterionchannel.com/i-was-a-teena...,4.5,729,56,"music, musical, score, cinematic, song, jazz, ...",-0.80,1.000000
562,Hunter in the Dark,Hideo Gosha,Japan,1979,1970s,2:17,"In Hideo Gosha's film, loyalty and ambition le...",https://www.criterionchannel.com/hunter-in-the...,6.9,425,81,"samurai, godzilla, monster, series, make, eart...",-0.75,0.750000
1354,Walpurgis Night,Gustaf Edgren,Sweden,1935,1930s,1:19,Meant as a day to celebrate the arrival of spr...,https://www.criterionchannel.com/walpurgis-night,6.0,317,10,"wife, home, marriage, desperate, charles, leaf...",-0.60,0.933333
210,Checking Out,David Leland,United States,1989,1980s,1:35,"After his friend suffers a fatal heart attack,...",https://www.criterionchannel.com/checking-out,4.8,396,11,"work, heart, deeply, beloved, run, owner, henr...",-0.60,0.700000
218,Chinese Odyssey 2002,Jeffrey Lau,Hong Kong,2002,2000s,1:30,"An Emperor and a princess, both desperate for ...",https://www.criterionchannel.com/chinese-odyss...,7.0,2312,15,"death, classic, power, final, maria, john, ric...",-0.60,1.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1228,Tales of a Golden Geisha,Juzo Itami,Japan,1990,1990s,1:58,Nobuko Miyamoto stars as a geisha who brings g...,https://www.criterionchannel.com/tales-of-a-go...,6.4,214,81,"samurai, godzilla, monster, series, make, eart...",0.70,0.600000
1137,"Sing, Young People!",Keisuke Kinoshita,Japan,1963,1960s,1:26,A college student receives a surprising offer ...,https://www.criterionchannel.com/sing-young-pe...,6.3,55,98,"young, student, kinoshita, friend, directed_ke...",0.70,0.500000
1368,Welcome Danger,Clyde Bruckman,United States,1929,1920s,1:54,"Harold Bledsoe, a botanist and the son of a su...",https://www.criterionchannel.com/welcome-danger,6.0,687,24,"force, crime, seemingly, north, english, clima...",0.75,0.950000
714,Lone Wolf and Cub: Sword of Vengeance,Kenji Misumi,Japan,1972,1970s,1:23,The inaugural film in the LONE WOLF AND CUB se...,https://www.criterionchannel.com/lone-wolf-and...,7.8,7247,56,"music, musical, score, cinematic, song, jazz, ...",0.80,0.916667
1282,Tokyo-ga,Wim Wenders,West Germany,1985,1980s,1:33,On the streets of Tokyo and in meetings with s...,https://www.criterionchannel.com/tokyo-ga,7.4,2639,92,"legendary, jean, mysterious, writer, world, ar...",1.00,1.000000

In [129]:
#load VADER
analyzer = SentimentIntensityAnalyzer()
#Add VADER metrics to dataframe
df['compound'] = [analyzer.polarity_scores(v)['compound'] for v in df['Description']]
df['neg'] = [analyzer.polarity_scores(v)['neg'] for v in df['Description']]
df['neu'] = [analyzer.polarity_scores(v)['neu'] for v in df['Description']]
df['pos'] = [analyzer.polarity_scores(v)['pos'] for v in df['Description']]
df.head(3)

,Title,Director,Country,Year,Decade,Duration,Description,Total Hours,Url,movieId,tb_Pol,tb_Subj,compound,neg,neu,pos
0,2 or 3 Things I Know About Her,Jean-Luc Godard,France,1967,1960s,1:27,In 2 OR 3 THINGS I KNOW ABOUT HER (2 OU 3 CHOS...,1.45,https://www.criterionchannel.com/2-or-3-things...,1,0.253333,0.443333,0.6486,0.030,0.906,0.064
1,3 Faces,Jafar Panahi,Iran,2018,2010s,1:40,Iranian master Jafar Panahi’s fourth feature s...,1.67,https://www.criterionchannel.com/3-faces,2,0.022727,0.475758,-0.4810,0.117,0.782,0.101
2,"4 Months, 3 Weeks and 2 Days",Cristian Mungiu,Romania,2007,2000s,1:53,Romanian filmmaker Cristian Mungiu shot to int...,1.88,https://www.criterionchannel.com/4-months-3-we...,3,-0.275000,0.541667,0.1406,0.068,0.869,0.064

In [ ]:
#performing content based recommendation

In [130]:
tfidf = TfidfVectorizer( stop_words='english' )

tfidf_matrix = tfidf.fit_transform(df['Description'])
tfidf_matrix.shape

(1620, 16988)

In [131]:
cosine_sim = linear_kernel(tfidf_matrix, tfidf_matrix)
cosine_sim.shape

(1620, 1620)

In [132]:
indices = pd.Series(df.index, index=df['Title']).drop_duplicates()
def get_recommendations(title,cosine_sim = cosine_sim):
    idx = indices[title]
    sim_scores = list(enumerate(cosine_sim[idx]))
    sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)
    sim_scores = sim_scores[1:11]
    movie_indices = [i[0] for i in sim_scores]
    return df['Title'].iloc[movie_indices],df['tb_Pol'].iloc[movie_indices]

In [133]:
#Now to get recommendations one will input the movie title and our recommender will generate top 10 movies similar to the input movie based on similar plots or stories¶
get_recommendations('The Olympic Games, Amsterdam, 1928')

(5                            The IX Olympiad at Amsterdam
 484                                    Fight Without Hate
 72                                Atlanta’s Olympic Glory
 9                                        16 Days of Glory
 1563                                    The White Stadium
 1215    Salt Lake City 2002: Bud Greenspan’s Stories o...
 189     Bud Greenspan’s Torino 2006: Stories of Olympi...
 1086                                People, Hopes, Medals
 1474                                      A Turning Point
 187     Bud Greenspan Presents Vancouver 2010, Stories...
 Name: Title, dtype: object,
 5       0.127381
 484     0.083636
 72     -0.166667
 9       0.100000
 1563    0.053333
 1215    0.095000
 189     0.275000
 1086    0.062500
 1474    0.000000
 187     0.125000
 Name: tb_Pol, dtype: float64)

In [ ]:
#trying to merge rating data frame for collaborative filtering

In [99]:
ratings = pd.read_csv("ratings.csv")
movies = pd.read_csv("movie.csv")

dataset = pd.merge(movies, ratings, how="left" , on=['movieId'])
dataset = dataset.loc[:,["userId","movieId","Title","Description","rating"]]
df_ratings = dataset.loc[:,["title","rating"]].groupby("title").mean()
genres = dataset["Description"]
dataset

,userId,movieId,Title,Description,rating
0,2.0,1,2 or 3 Things I Know About Her,In 2 OR 3 THINGS I KNOW ABOUT HER (2 OU 3 CHOS...,5.0
1,5.0,1,2 or 3 Things I Know About Her,In 2 OR 3 THINGS I KNOW ABOUT HER (2 OU 3 CHOS...,4.0
2,8.0,1,2 or 3 Things I Know About Her,In 2 OR 3 THINGS I KNOW ABOUT HER (2 OU 3 CHOS...,5.0
3,11.0,1,2 or 3 Things I Know About Her,In 2 OR 3 THINGS I KNOW ABOUT HER (2 OU 3 CHOS...,4.0
4,14.0,1,2 or 3 Things I Know About Her,In 2 OR 3 THINGS I KNOW ABOUT HER (2 OU 3 CHOS...,4.0
...,...,...,...,...,...
40546,607.0,1620,Zombi Child,Iconoclastic auteur Bertrand Bonello blends vo...,3.0
40547,615.0,1620,Zombi Child,Iconoclastic auteur Bertrand Bonello blends vo...,4.0
40548,627.0,1620,Zombi Child,Iconoclastic auteur Bertrand Bonello blends vo...,3.0
40549,662.0,1620,Zombi Child,Iconoclastic auteur Bertrand Bonello blends vo...,4.0
40550,668.0,1620,Zombi Child,Iconoclastic auteur Bertrand Bonello blends vo...,3.0

In [100]:
from nltk.stem import WordNetLemmatizer
lemmatizer = WordNetLemmatizer()
li = []
for i in range(len(genres)):
    temp = genres[i].split(" ")
    for j in range(len(temp)):
        temp[j] = lemmatizer.lemmatize(temp[j])
    li.append(" ".join(temp))
print(li)

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)

In [101]:
from sklearn.feature_extraction.text import CountVectorizer

cv = CountVectorizer()
X = cv.fit_transform(li).toarray()

genres = pd.DataFrame(X,columns=cv.get_feature_names())

dataset = dataset.iloc[:,:-2]
new_dataset = dataset.join(genres)

In [97]:
new_dataset

,userId,movieId,Title,000,10,100,1000,1080,11,125th,...,zouzou,zsigmond,zsófia,zwerin,ágnes,ángel,åke,élan,émigré,šerbedžija
0,2.0,1,2 or 3 Things I Know About Her,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,5.0,1,2 or 3 Things I Know About Her,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,8.0,1,2 or 3 Things I Know About Her,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,11.0,1,2 or 3 Things I Know About Her,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,14.0,1,2 or 3 Things I Know About Her,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40546,607.0,1620,Zombi Child,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
40547,615.0,1620,Zombi Child,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
40548,627.0,1620,Zombi Child,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
40549,662.0,1620,Zombi Child,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
40550,668.0,1620,Zombi Child,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0